# Generated by Django 5.1.4 on 2025-01-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                help_text="Product slug",
                unique=True,
                verbose_name="slug",
            ),
        ),
    ]
