# Generated by Django 5.1.4 on 2025-01-09 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "Comment", "verbose_name_plural": "Comments"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
    ]
