# Generated by Django 5.1.4 on 2025-01-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0004_alter_comment_options_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(
                help_text="Comment body", max_length=1000, verbose_name="body"
            ),
        ),
    ]
